-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/attrs.pl
-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/gv.pl
-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/makerand.pl
-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/pack.pl
-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/redef.pl
-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/ref.pl
-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/regmesg.pl
-I. -I./lib $SPEC_DIR/benchspec/CPU2006/400.perlbench/data/test/input/test.pl
