--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/ref/input/13x13.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/ref/input/nngs.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/ref/input/score2.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/ref/input/trevorc.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/ref/input/trevord.tst
