--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/test/input/capture.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/test/input/connect.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/test/input/connect_rot.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/test/input/connection.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/test/input/connection_rot.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/test/input/cutstone.tst
--quiet --mode gtp < $SPEC_DIR/benchspec/CPU2006/445.gobmk/data/test/input/dniwog.tst
